# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Eclipse Ecore Plugin
author: Proceso de instalación y ejemplo práctico de plugin Ecore
logo: logo.png

# Information about where the book exists on the web
repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
